# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-26 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190622_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
    ]
