# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-07-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190626_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('update_email', '修改邮箱'), ('forget', '找回密码')], max_length=20, verbose_name='发送类型'),
        ),
    ]
